### ISSUE TITLE
Dealing with hard constraints and ub in CFN format (and pytb2 ?)

### ISSUE THREAD

**Issue by tschiex** [toulbar2/toulbar2#12]
It would be great to have an "infinity" cost available (one that is equal to the initial global ub, w/o knowing this ub). When a CFN is written down in CFN format, we put a ub and use it in the CFN. Then later one edits this CFN and let say, adds a cost function to it, but the "ub" is not valid anymore. Not only the ub cost has to be changed in the header but also in all the cost functions. It's a pain. It's also the case if we merge 2 CFNs, we would need to add the 2 ubs together and propagate this in all cost functions that were hard. If we could use "inf" as a cost in the CFN format or possibly in pytb2 (even if a finite cost is used internally), meaning "current ub",  this would simplify the writing/editing/merging.

**Comment by toulbar2** [comment]
CFN costs admit "inf" string to represent unfeasible assignments.
