### ISSUE TITLE
Wrong CFN dump in maximization

### ISSUE THREAD

**Issue by toulbar2** [toulbar2/toulbar2#21]
In maximization, function dump_CFN will return always negative costs inside all cost functions. The problem is no more equivalent. See example:
> ./toulbar2 validation/default/maximization.cfn -x=,0=0,1=1
-4
> ./toulbar2 validation/default/maximization.cfn -z=3
> ./toulbar2 problem.cfn -x=,0=0,1=1
No solution

**Comment by tschiex** [comment]
The dump looks correct and the issue lies in the CFN reader (see commit  23408db49e4e3d1b3b22ec02cb891dcb08a9a933).
