### ISSUE TITLE
Some "costs" arrays ending as ",]" into .cfn

### ISSUE THREAD

**Issue by nrousse** [toulbar2/toulbar2#22]
Some "costs" arrays end as ",]" into foo_json.cfn file made by `toulbar2 foo.cfn -z=foo_json.cfn`

It is in relation with the code 
```
if (printed)
    os << ",\n";
```
into the method : void TernaryConstraint::dump_CFN(ostream& os, bool original)

**Comment by toulbar2** [comment]
Corrected in commit 1ae662a2ac49ddf2e03ce1ad2801e7d160fee74e
