### ISSUE TITLE
Getting the lower bound via API after resolution

### ISSUE THREAD

**Issue by smbct** [toulbar2/toulbar2#23]
In case an instance would not be solved to optimality, it could be interesting to access the final lower bound. Although the optimality gap is shown in the output (var globalLowerBound from Solver::showGap function), there do not seem to be any function for this purpose in the API.

**Comment by toulbar2** [comment]
Add a specific getDDualBound function (see GetDDualBound in python) in class WeightedCSPSolver to report the problem dual bound found at the end of an interrupted search.
