### ISSUE TITLE
save cfn after preprocessing

### ISSUE THREAD

**Issue by dallouche** [toulbar2/toulbar2#25]
-z=4 allows to save cfn file after preprocessing.
but assigned variables a lost!

keep variables with the assigned values will fix the problem and keep the final solution integrity.

**Comment by dallouche** [comment]
==> variables with 1 the assigned values in the output cfn files

**Comment by toulbar2** [comment]
When saved using -z=4, additional information is printed about removed variables:

> toulbar2 validation/default/1aho.cfn.gz -z=4
Read 64 variables, with 55 values at most, and 608 cost functions, with maximum arity 2.
...
Warning, the following variables have been assigned or eliminated ("*") and are not part of the output CFN:
 V1=V0 K2=K32 D3=D14 G4=G0 D8=D0 V10=V2 N11=N8 C12=C2 G17=G0 N19=N0 A20=A0 N23=N11 K30=K23 G31=G0 G34=G0 Q37=Q50 A39=A0 S40=S36 P41=P2 G43=G0 A45=A0 L51=L0 P52=P2 D53=D7 H54=H0 V55=V1 T57=T8 G59=G0 P60=P0 G61=G0 C63=C1

This information can be used (if no variables have been eliminated with an "*", use option -e: -f: -p: to be safe) to recover a complete solution to the original problem:
> toulbar2 problem.cfn -w=3
Read 33 variables, with 50 values at most, and 175 cost functions, with maximum arity 2.
...
Optimum: -33.729920 in 10 backtracks and 27 nodes ( 30 removals by DEE) and 0.263 seconds.

> echo " V1=V0 K2=K32 D3=D14 G4=G0 D8=D0 V10=V2 N11=N8 C12=C2 G17=G0 N19=N0 A20=A0 N23=N11 K30=K23 G31=G0 G34=G0 Q37=Q50 A39=A0 S40=S36 P41=P2 G43=G0 A45=A0 L51=L0 P52=P2 D53=D7 H54=H0 V55=V1 T57=T8 G59=G0 P60=P0 G61=G0 C63=C1" >> sol
> toulbar2 validation/default/1aho.cfn.gz -x
Read 64 variables, with 55 values at most, and 608 cost functions, with maximum arity 2.
 Input solution cost: -33.729920 (nb. of unassigned variables: 0)
