### ISSUE TITLE
Cover test fails

### ISSUE THREAD

**Issue by smbct** [toulbar2/toulbar2#26]
The test "Phase2_10_1.bep_2" fails during testing: (instance 10_1.bep, option -v=2)

79/207 Test  #79: Phase2_10_1.bep_2 ..................................Subprocess aborted***Exception:   0.01 sec

Details: 
- toulbar2/src/core/tb2wcsp.hpp:261: virtual unsigned int WCSP::toIndex(int, Value): Assertion `vars[varIndex]->enumerated()' failed
- An interval variable is created in BEP::read() because of boolean variable BAC (see tb2bep.cpp)

**Comment by toulbar2** [comment]
Resolved.
