### ISSUE TITLE
toulbar2 reference manual failing to build in Debian sid.

### ISSUE THREAD

**Issue by plugwash** [toulbar2/toulbar2#3]
toulbar2 is currently failing to build in Debian sid with latex errors.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920459

[...]
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./index.tex
(/usr/share/texlive/texmf-dist/tex/latex/wasysym/uwasy.fd)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd)
! Missing } inserted.
<inserted text>
                }
l.7 \end{longtabu}

?
! Emergency stop.
<inserted text>
                }
l.7 \end{longtabu}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on refman.log.
make[4]: *** [Makefile:6: refman.pdf] Error 1
make[4]: Leaving directory
'/<<BUILDDIR>>/toulbar2-1.0.0+dfsg3/obj-x86_64-linux-gnu/latex'
make[3]: *** [CMakeFiles/doc.dir/build.make:71: doc] Error 2
make[3]: Leaving directory '/<<BUILDDIR>>/toulbar2-1.0.0+dfsg3/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/doc.dir/all] Error 2
[...]

**Comment by toulbar2** [comment]
Yes. This is a bug introduced in the debian latex distribution that affects all users of doxygen. Upstream texlive is working on it I have been said.

**Comment by toulbar2** [comment]
Just tested on a fresh debian image and noticed texlive maintainers did solve this issue. Toulbar2 doc now compiles fine using texlive 2018.20190227-2 version.
