### ISSUE TITLE
Strange behavior of Dump() in pytoulbar2 - WCSP format

### ISSUE THREAD

**Issue by treepleks** [toulbar2/toulbar2#32]
Using M. Defresne code for learning how to play the Sudoku, when saving the generated CFNs in wcsp format using CFN.Dump(), the resulting wcsp file contains variables with 10 values instead of 9 (and apparently a spurious zero cost solution with all zeros).

Instaed, saving as a CFN file and then translating as WCSP using tb2 -z=1 saves a correct WCSP file apparently.

**Comment by toulbar2** [comment]
wcsp format always assumes domain starts from zero. when dump in wcsp format is performed before preprocessing, domain sizes are set to max(domain)+1 and not max(domain)-min(domain)+1. Additional unary cost functions are added to forbid the removed values. cfn format avoids this issue.
