### ISSUE TITLE
ARM64 compatibility

### ISSUE THREAD

**Issue by g-poveda** [toulbar2/toulbar2#33]
Hi, i tried installing toulbar2 and/or pytoulbar2 in a mac os ARM machine but failed.
On pip there is no wheel provided so tried to compile from source. 
I will provide an error log in a following message, it fails in the middle of the compilation, it may be possible to solve.
I would like to know if you aim to make toulbar2 compatible with such architecture in the near future. 
Cheers

**Comment by toulbar2** [comment]
Ok to have look to the failure message. I have no access to mac os ARM.

**Comment by g-poveda** [comment]
thanks, i had some email exchange with some of you, 

`ld: Undefined symbols:
  _lzma_cputhreads, referenced from:
      boost::iostreams::detail::lzma_base::do_init(boost::iostreams::lzma_params const&, bool, void* (*)(void*, unsigned long, unsigned long), void (*)(void*, void*), void*) in tb2reader.cpp.o
  _lzma_stream_encoder_mt, referenced from:
      boost::iostreams::detail::lzma_base::init_stream(bool) in tb2reader.cpp.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/Darwin/toulbar2] Error 1
make[1]: *** [CMakeFiles/toulbar2.dir/all] Error 2
make: *** [all] Error 2`

my error seems similar to the one on the other issue so i will look. for info i already tried the flag "-DNO_LZMA" but it's ignored in the cmakefile so didn't work. Will try the solution of the other issue ;)

**Comment by toulbar2** [comment]
I have modified the code by removing addAMOConstraints() in case flag -DBOOST is missing (i.e. cmake -DBoost=OFF). It should compile now.

**Comment by g-poveda** [comment]
Hi, thank you @toulbar2 indeed it is finally working !

**Comment by toulbar2** [comment]
To sum-up, using cmake -DBoost=OFF .. allows to compile toulbar2 on Mac with ARM64.
