### ISSUE TITLE
dunamic library

### ISSUE THREAD

**Issue by YuxuanXie** [toulbar2/toulbar2#4]
Could you please show me how can I generate a dynamic library such as tb2.so?

**Comment by dallouche** [comment]
Hi ,

you must try :


cmake .. -DTOULBAR2_ONLY:BOOL=OFF -DLIBTB2:BOOL=ON

make

...

ls lib/Linux/
libtb2.so*



toublar2/src/toulbar2test.cpp


provides a example howto use the library


cheers david

________________________________
De : YX_Xie <notifications@github.com>
Envoyé : mardi 1 octobre 2019 23:37
À : toulbar2/toulbar2
Cc : Subscribed
Objet : [toulbar2/toulbar2] dunamic library (#4)


Could you please show me how can I generate a dynamic library such as tb2.so?

-

**Comment by YuxuanXie** [comment]
Hi,

Thak you very much! I tried as you said and got the libtb2.so.

Best Regard,
XIE

**Comment by toulbar2** [comment]
In the new CMakeLists.txt, just do cmake -DLIBTB2=ON to get libtb2.so and cmake -DPYTB2=ON -DMPI=OFF to get pytoulbar2.*.so for python module import. Libraries are compiled in ./lib/Linux directory.
