### ISSUE TITLE
Using a particular algorithm for logZ computation

### ISSUE THREAD

**Issue by durgeshra** [toulbar2/toulbar2#6]
Hi,
I want to use "Guaranteed Weighted Counting for Affinity Computation: Beyond Determinism and Structure" for Partition Function computation on graphical models (.uai) files. However, I could not find a flag for the same in the help message.
I'd appreciate any help in this regard.
Thanks!

**Comment by toulbar2** [comment]
Here they are: 
  -logz : computes log of probability of evidence (i.e. log partition function or log(Z) or PR task) for graphical models only (problem file extension .uai)
   -epsilon=[float] : approximation factor for computing the partition function (should be greater than 1, default value is infinity)
