### ISSUE TITLE
Issue installing toulbar2 on Mac

### ISSUE THREAD

**Issue by petrovaleksandra** [toulbar2/toulbar2#7]
Hi,

My current OS is Catalina 10.15.7. I have run into the following issue while compiling the toulbar2 after running the command make (everything else compiles well until this point):

Undefined symbols for architecture x86_64:
  "_lzma_cputhreads", referenced from:
      boost::iostreams::detail::lzma_base::do_init(boost::iostreams::lzma_params const&, bool, void* (*)(void*, unsigned long, unsigned long), void (*)(void*, void*), void*) in tb2reader.cpp.o
  "_lzma_stream_encoder_mt", referenced from:
      boost::iostreams::detail::lzma_base::reset(bool, bool) in tb2reader.cpp.o
      boost::iostreams::detail::lzma_base::init_stream(bool) in tb2reader.cpp.o
      boost::iostreams::detail::lzma_base::do_init(boost::iostreams::lzma_params const&, bool, void* (*)(void*, unsigned long, unsigned long), void (*)(void*, void*), void*) in tb2reader.cpp.o
ld: symbol(s) not found for architecture x86_64

**Comment by toulbar2** [comment]
Hi,
I assume you follow ./toulbar2/misc/script/MacOS-requirements-install.sh installation procedure.
if it still does not work, try cmake -DBOOST=NO ..
it should compile without BOOST dependency nor LZMA. you will have to uncompress problem files before solving them.
cheers, Simon.

**Comment by petrovaleksandra** [comment]
Thank you for the help.

Yes I followed and installed the libraries already before the issue appeared. I used the command you suggested, the same issue still persists. I have the newest version of xz (XZ Utils): 5.2.5 and liblzma: 5.2.5 in case that may be related to the issue.

**Comment by toulbar2** [comment]
Sorry, the correct flag should be -DBoost=OFF

**Comment by tschiex** [comment]
To add to Simon's answer (I hope you followed the MacOS requirements txt).

The issue likely lies in the version of boost you are using. 
Essentially, Boost changed its "API" for LZMA at some point and we try 
to detect "when" this change appears. This is tested in

     toulbar2/src/utils/lzma-cpp.inc

Apparently the version of boost you are using does not offer the 
"_lzma_cputhreads" that is expected in recent versions of Boost. It may 
be for various reasons. Possibly, editing 
toulbar2/src/utils/lzma-cpp.inc and replacing the first line:

     #if (BOOST_VERSION > 107000)

by

     #if 0

could make it.

Thomas

Le 20/11/2020 à 13:50, petrovaleksandra a écrit :

**Comment by petrovaleksandra** [comment]
Thank you very much for the help! Changing the code helped resolve the issue.

Best,
Aleksandra
